'use strict';
const $=id=>document.getElementById(id);
const brand=$('brand'),typeSel=$('type'),seriesSel=$('series'),modelSel=$('model'),symptom=$('symptom'),productInfo=$('productInfo'),search=$('modelSearch'),matches=$('matches');
let current=null,currentProduct=null,answers={};
function uniq(a){return [...new Set(a)]}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function setSelect(el,items,placeholder,enabled=true){el.innerHTML=`<option value="">${esc(placeholder)}</option>`+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');el.value='';el.disabled=!enabled}
function clearSelect(el,p){setSelect(el,[],p,false)}
function resetDiag(){current=null;answers={};$('tab-diag').innerHTML='<div class="empty"><div class="big">🔧</div><b>先從左側選擇設備與症狀</b><br><span class="small">也可以直接輸入型號搜尋。</span></div>'}
function resetSelectors(){brand.value='';clearSelect(typeSel,'請先選擇品牌');clearSelect(seriesSel,'請先選擇機型類別');clearSelect(modelSel,'請先選擇產品系列');clearSelect(symptom,'請先選擇實際型號');currentProduct=null;renderProductInfo()}
function updateTypes(){clearSelect(seriesSel,'請先選擇機型類別');clearSelect(modelSel,'請先選擇產品系列');clearSelect(symptom,'請先選擇實際型號');currentProduct=null;renderProductInfo();if(!brand.value)return;setSelect(typeSel,uniq(PRODUCTS.filter(p=>p.b===brand.value).map(p=>p.t)),'請選擇機型類別')}
function updateSeries(){clearSelect(modelSel,'請先選擇產品系列');clearSelect(symptom,'請先選擇實際型號');currentProduct=null;renderProductInfo();if(!brand.value||!typeSel.value)return;setSelect(seriesSel,uniq(PRODUCTS.filter(p=>p.b===brand.value&&p.t===typeSel.value).map(p=>p.s)),'請選擇產品系列')}
function updateModels(){clearSelect(symptom,'請先選擇實際型號');currentProduct=null;renderProductInfo();if(!brand.value||!typeSel.value||!seriesSel.value)return;setSelect(modelSel,PRODUCTS.filter(p=>p.b===brand.value&&p.t===typeSel.value&&p.s===seriesSel.value).map(p=>p.m),'請選擇實際型號')}
function updateProduct(){currentProduct=PRODUCTS.find(p=>p.b===brand.value&&p.t===typeSel.value&&p.s===seriesSel.value&&p.m===modelSel.value)||null;renderProductInfo();if(!currentProduct){clearSelect(symptom,'請先選擇實際型號');return}const extra=EXTRA_SYMPTOMS[`${brand.value}|${modelSel.value}`]||[];setSelect(symptom,uniq([...extra,...Object.keys(GENERIC)]),'請選擇故障症狀')}
function renderProductInfo(){if(!currentProduct){productInfo.innerHTML='';return}const c=currentProduct.status==='已停產'?'stop':currentProduct.status==='維修常見舊機'?'legacy':'';productInfo.innerHTML=`<div class="product-card"><div class="product-head"><div><div class="product-model">${esc(currentProduct.m)}</div><div class="chips"><span class="chip">${esc(currentProduct.b)}</span><span class="chip">${esc(currentProduct.t)}</span><span class="chip">${esc(currentProduct.s)}</span><span class="chip ${c}">${esc(currentProduct.status)}</span></div></div><a class="source-link" href="${BRAND_URLS[currentProduct.b]}" target="_blank" rel="noopener">萬里官網 ↗</a></div>${currentProduct.note?`<div class="product-note">${esc(currentProduct.note)}</div>`:''}</div>`}
function selectProduct(p){resetDiag();brand.value=p.b;updateTypes();typeSel.value=p.t;updateSeries();seriesSel.value=p.s;updateModels();modelSel.value=p.m;updateProduct();search.value=p.m;matches.style.display='none'}
function setupSearch(){search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();if(!q){matches.style.display='none';return}const found=PRODUCTS.filter(p=>`${p.b} ${p.s} ${p.m}`.toLowerCase().includes(q)).sort((a,b)=>{const am=a.m.toLowerCase(),bm=b.m.toLowerCase();const ae=am===q?0:am.startsWith(q)?1:2,be=bm===q?0:bm.startsWith(q)?1:2;return ae-be||am.length-bm.length||am.localeCompare(bm)}).slice(0,15);matches.innerHTML=found.map(p=>`<div class="match" data-i="${PRODUCTS.indexOf(p)}"><b>${esc(p.m)}｜${esc(p.b)}</b><span>${esc(p.t)}・${esc(p.s)}・${esc(p.status)}</span></div>`).join('')||'<div class="match"><span>找不到型號。</span></div>';matches.style.display='block';matches.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>selectProduct(PRODUCTS[+el.dataset.i]))});document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))matches.style.display='none'})}
function startCase(){if(!currentProduct||!symptom.value){toast('請先選完整設備與故障症狀');return}current=MODEL_CASES[`${brand.value}|${modelSel.value}|${symptom.value}`]||GENERIC[symptom.value];if(!Array.isArray(current)){toast('此流程資料異常');return}answers={};showTab('diag',document.querySelector('.tab'));renderDiag()}
function renderDiag(){if(!current)return resetDiag();const done=Object.keys(answers).length,pct=Math.round(done/current.length*100);let html=`<div class="hero"><div><span class="badge">${esc(brand.value)}｜${esc(typeSel.value)}｜${esc(seriesSel.value)}</span><h1>${esc(modelSel.value)}｜${esc(symptom.value)}</h1><div class="small">${esc(currentProduct?.status||'')}・已完成 ${done}/${current.length} 項</div></div><button class="btn secondary no-print" onclick="makeReport(true)">複製維修摘要</button></div><div class="progress"><div style="width:${pct}%"></div></div><div class="steps">`;current.forEach((s,i)=>{const cmd=s[3]&&String(s[3]).startsWith('^')?s[3]:'',tip=s[3]&&!cmd?s[3]:'';html+=`<div class="step ${answers[i]?'done':''}"><div class="stephead"><div class="num">${i+1}</div><div><div class="stitle">${esc(s[0])}</div><div class="desc">${esc(s[1])}</div></div></div><div class="answers">${s[2].map(a=>`<button class="ans ${answers[i]===a?'active':''}" onclick='setAns(${i},${JSON.stringify(a)})'>${esc(a)}</button>`).join('')}</div>${tip?`<div class="tip">💡 ${esc(tip)}</div>`:''}${cmd?`<div class="cmd"><button class="copy" onclick='copyText(${JSON.stringify(cmd)})'>複製</button>${esc(cmd)}</div>`:''}</div>`});html+='</div>'+diagnose()+'<div id="reportBox"></div>';$('tab-diag').innerHTML=html}
function setAns(i,a){answers[i]=a;renderDiag()}
function diagnose(){const vals=Object.values(answers);if(!vals.length)return'';const hints=[];if(vals.some(v=>v.includes('固定／幾乎不變')))hints.push('Sensor 數值無變化：優先查 Sensor、本體接頭、線材與輸入電路。');if(vals.some(v=>v.includes('拔除後行為正常很多')))hints.push('隔離 Sensor 後明顯改善：Sensor／線路為高優先嫌疑。');if(vals.some(v=>v.includes('差異很小／沒有')))hints.push('Media Sensor 無法可靠區分耗材：查位置、污染、紙材與 Sensor。');if(vals.some(v=>v.includes('開始破碳')||v.includes('約 20 已破碳')))hints.push('已有過熱／破碳：不要再只加濃度，改查耗材、壓力、印字頭與滾輪。');if(vals.some(v=>v.includes('固定區域淡')||v.includes('固定同位置')))hints.push('固定區域異常：提高 Printhead、Platen Roller 或壓力不均嫌疑。');if(!hints.length)hints.push(Object.keys(answers).length===current.length?'基本排查已完成，依異常結果由設定／耗材 → 感應器／機構 → 線路／主板處理。':'繼續完成剩餘步驟。');return `<div class="result info"><h3>目前判斷</h3><ul>${hints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="btnrow no-print" style="margin-top:10px"><button class="btn primary" onclick="makeReport(true)">複製完整維修紀錄</button><button class="btn secondary" onclick="window.print()">列印／存 PDF</button><button class="btn ghost" onclick="saveCase()">儲存案件</button></div></div>`}
function reportText(){const lines=['【標籤機故障排查紀錄】',`日期：${new Date().toLocaleString('zh-TW')}`,`客戶：${$('customer').value.trim()||'未填'}`,`工程師：${$('engineer').value.trim()||'未填'}`,`設備：${brand.value} ${modelSel.value}`,`類別／系列：${typeSel.value}／${seriesSel.value}`,`產品狀態：${currentProduct?.status||''}`,`序號：${$('serial').value.trim()||'未填'}`,`症狀：${symptom.value}`,'','檢查結果：'];if(current)current.forEach((s,i)=>lines.push(`${i+1}. ${s[0]}：${answers[i]||'尚未確認'}`));lines.push('',`額外觀察：${$('notes').value.trim()||'無'}`);return lines.join('\n')}
function makeReport(copy=false){const t=reportText(),box=$('reportBox');if(box)box.innerHTML=`<div class="report">${esc(t)}</div>`;if(copy)copyText(t)}
function copyText(t){if(navigator.clipboard&&location.protocol!=='file:')navigator.clipboard.writeText(t).then(()=>toast('已複製')).catch(()=>fallbackCopy(t));else fallbackCopy(t)}
function fallbackCopy(t){const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('已複製')}
function readCases(){try{return JSON.parse(localStorage.getItem('printer_engineer_cases')||'[]')}catch{return[]}}
function saveCase(){if(!current)return toast('請先開始一個排查案件');const list=readCases();list.unshift({time:new Date().toLocaleString('zh-TW'),model:modelSel.value,symptom:symptom.value,customer:$('customer').value.trim(),text:reportText()});try{localStorage.setItem('printer_engineer_cases',JSON.stringify(list.slice(0,30)));toast('案件已儲存在此瀏覽器');showHistory()}catch{toast('無法儲存本機紀錄')}}
function showHistory(){const list=readCases();$('historyBox').innerHTML=list.length?`<div class="history">${list.map((x,i)=>`<div class="hist" onclick="copySaved(${i})"><b>${esc(x.model)}｜${esc(x.symptom)}</b><div>${esc(x.time)}${x.customer?'・'+esc(x.customer):''}</div></div>`).join('')}</div><button class="btn danger" style="margin-top:8px;width:100%" onclick="clearHistory()">清除本機紀錄</button>`:'<div class="small" style="margin-top:8px">目前沒有已儲存案件。</div>'}
function copySaved(i){const x=readCases()[i];if(x)copyText(x.text)}
function clearHistory(){if(confirm('確定清除本機維修紀錄？')){localStorage.removeItem('printer_engineer_cases');showHistory()}}
function showTab(name,btn){document.querySelectorAll('.toolbox').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('tab-'+name).classList.add('active');if(btn)btn.classList.add('active')}
function renderTools(){$('tab-tools').innerHTML=`<div class="hero"><div><span class="badge">工程師工具</span><h1>常用指令與現場原則</h1></div></div><div class="command-card"><b>Zebra｜短校正</b><div class="cmd"><button class="copy" onclick="copyText('^XA^MFS,S^JUS^XZ')">複製</button>^XA^MFS,S^JUS^XZ</div></div><div class="command-card"><b>Zebra｜恢復完整校正</b><div class="cmd"><button class="copy" onclick="copyText('^XA^MFC,C^JUS^XZ')">複製</button>^XA^MFC,C^JUS^XZ</div></div><div class="result info"><h3>現場先做</h3><ul><li>拍下錯誤畫面與完整型號。</li><li>確認最近是否換耗材、電腦、網路或設定。</li><li>先印機器自身測試頁，切開硬體與電腦／軟體問題。</li><li>校正前先確認 Sensor 位置。</li><li>拆機前記錄原設定與線路位置。</li></ul></div>`}
function renderCatalog(){const brands=uniq(PRODUCTS.map(p=>p.b));$('tab-catalog').innerHTML=`<div class="hero"><div><span class="badge">設備資料庫</span><h1>標籤條碼列印機型號總覽</h1><div class="small">${brands.length} 品牌・${PRODUCTS.length} 型號</div></div></div>`+brands.map(b=>`<div class="catalog-brand"><h3>${esc(b)}</h3>${uniq(PRODUCTS.filter(p=>p.b===b).map(p=>p.t)).map(t=>`<div class="catalog-type">${esc(t)}</div>`+uniq(PRODUCTS.filter(p=>p.b===b&&p.t===t).map(p=>p.s)).map(s=>`<div class="series-row"><span class="series-name">${esc(s)}：</span> ${PRODUCTS.filter(p=>p.b===b&&p.t===t&&p.s===s).map(p=>`<span class="modelpill ${p.status==='已停產'?'stop':p.status==='維修常見舊機'?'legacy':''}">${esc(p.m)}</span>`).join('')}</div>`).join('')).join('')}</div>`).join('')}
function resetCase(){resetDiag();search.value='';matches.style.display='none';resetSelectors()}
function toast(t){const x=document.createElement('div');x.textContent=t;x.style='position:fixed;left:50%;bottom:25px;transform:translateX(-50%);background:#111827;color:#fff;padding:9px 14px;border-radius:9px;z-index:99;font-weight:800;font-size:12px';document.body.appendChild(x);setTimeout(()=>x.remove(),1400)}
function selfTest(){const problems=[];if(!Array.isArray(PRODUCTS)||PRODUCTS.length<100)problems.push('型號資料不足');for(const k of Object.keys(GENERIC))if(!Array.isArray(GENERIC[k]))problems.push(k);console.info('[engineer self-test]',{brands:uniq(PRODUCTS.map(p=>p.b)).length,products:PRODUCTS.length,problems})}
function init(){brand.onchange=()=>{resetDiag();updateTypes()};typeSel.onchange=()=>{resetDiag();updateSeries()};seriesSel.onchange=()=>{resetDiag();updateModels()};modelSel.onchange=()=>{resetDiag();updateProduct()};symptom.onchange=resetDiag;setupSearch();renderTools();renderCatalog();showHistory();$('headerStat').textContent=`${uniq(PRODUCTS.map(p=>p.b)).length} 品牌・${PRODUCTS.length} 型號`;selfTest()}
window.addEventListener('error',e=>console.error('Engineer tool error',e.message));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
