const BRAND_URLS={
  "Zebra":"https://www.far-beyound.com.tw/product/1/5",
  "Argox":"https://www.far-beyound.com.tw/product/1/6",
  "TSC":"https://www.far-beyound.com.tw/product/1/22",
  "GoDEX":"https://www.far-beyound.com.tw/product/1/23",
  "TOSHIBA":"https://www.far-beyound.com.tw/product/1/24",
  "SATO":"https://www.far-beyound.com.tw/product/1/28",
  "Honeywell (Datamax/Intermec)":"https://www.far-beyound.com.tw/product/1/29"
};
const PRODUCTS=[
{b:"Zebra",t:"工業型",s:"ZT600 系列",m:"ZT610",status:"官網產品頁",note:"ZT600 系列工業型"},{b:"Zebra",t:"工業型",s:"ZT600 系列",m:"ZT620",status:"官網產品頁",note:"ZT600 系列工業型"},{b:"Zebra",t:"工業型",s:"ZT500 系列",m:"ZT510",status:"官網產品頁",note:"105SL / 105SL Plus 升級方向"},{b:"Zebra",t:"工業型",s:"Xi4 系列",m:"220Xi4",status:"官網產品頁",note:"8 吋寬工業型；現場維修常見"},{b:"Zebra",t:"工業型",s:"Xi4 系列",m:"110Xi4",status:"維修常見舊機",note:"萬里官網配件頁仍列 Xi4 Series 印字頭；加入維修資料庫"},
{b:"Zebra",t:"商業型",s:"ZT400 系列",m:"ZT411",status:"官網產品頁"},{b:"Zebra",t:"商業型",s:"ZT400 系列",m:"ZT421",status:"官網產品頁"},{b:"Zebra",t:"商業型",s:"ZT200 系列",m:"ZT231",status:"官網產品頁",note:"ZT230 替代型號"},{b:"Zebra",t:"商業型",s:"ZT100 系列",m:"ZT111",status:"官網產品頁",note:"ZT210 / ZT220 替代型號"},{b:"Zebra",t:"商業型",s:"ZT200 系列（舊）",m:"ZT210",status:"已停產",note:"官網載明 2022/6 停產；替代 ZT111"},{b:"Zebra",t:"商業型",s:"ZT200 系列（舊）",m:"ZT220",status:"已停產",note:"官網載明 2022/6 停產；替代 ZT111"},{b:"Zebra",t:"商業型",s:"ZT200 系列（舊）",m:"ZT230",status:"已停產",note:"官網載明 2022/6 停產；替代 ZT231"},
{b:"Zebra",t:"桌上型",s:"ZD600 系列",m:"ZD621",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"ZD400 系列",m:"ZD421",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"ZD888",m:"ZD888TA",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"ZD200 系列",m:"ZD220",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"ZD200 系列",m:"ZD230",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"GX 系列",m:"GX420",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"GX 系列",m:"GX430",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"GK 系列",m:"GK420",status:"官網產品頁"},{b:"Zebra",t:"桌上型",s:"GT 系列",m:"GT800",status:"維修常見舊機",note:"萬里官網 Zebra 印字頭配件頁列出"},
{b:"Zebra",t:"攜帶型",s:"ZR600 系列",m:"ZR658",status:"官網產品頁"},{b:"Zebra",t:"攜帶型",s:"ZR600 系列",m:"ZR668",status:"官網產品頁"},{b:"Zebra",t:"攜帶型",s:"ZQ500 系列",m:"ZQ511",status:"官網產品頁"},{b:"Zebra",t:"攜帶型",s:"ZQ500 系列",m:"ZQ521",status:"官網產品頁"},{b:"Zebra",t:"攜帶型",s:"QLn 系列",m:"QLn420",status:"官網產品頁"},
{b:"Argox",t:"工業型",s:"iX4 Pro 系列",m:"iX4-200 Pro",status:"官網產品頁"},{b:"Argox",t:"工業型",s:"iX4 Pro 系列",m:"iX4-240 Pro",status:"官網產品頁"},{b:"Argox",t:"工業型",s:"iX4 Pro 系列",m:"iX4-250 Pro",status:"官網產品頁"},{b:"Argox",t:"工業型",s:"iX4 Pro 系列",m:"iX4-350 Pro",status:"官網產品頁"},
{b:"Argox",t:"桌上型",s:"P4 Pro 系列",m:"P4-250 Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"P4 Pro 系列",m:"P4-350 Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"P4 Pro 系列",m:"P4-650 Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"P4 系列（現場舊機）",m:"P4-650",status:"維修常見舊機",note:"保留你們現場既有 P4-650 維修情境"},{b:"Argox",t:"桌上型",s:"CX 系列",m:"CX-3140 Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"CX 系列",m:"CX-2140 Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"OS 系列",m:"OS-214EX Pro",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"CP 系列",m:"CP-2140EX",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"CP 系列",m:"CP-3140EX",status:"官網產品頁"},{b:"Argox",t:"桌上型",s:"CP 系列（舊）",m:"CP-3140L",status:"已停產",note:"接續型號 CX-3140 Pro"},{b:"Argox",t:"桌上型",s:"CP 系列（舊）",m:"CP-2140M",status:"已停產",note:"接續型號 CX-2140 Pro"},{b:"Argox",t:"桌上型",s:"OS 系列（舊）",m:"OS-214plus",status:"已停產",note:"接續型號 OS-214EX Pro"},
{b:"TSC",t:"工業型",s:"MH 系列",m:"MH241",status:"官網產品頁"},{b:"TSC",t:"工業型",s:"MH 系列",m:"MH341",status:"官網產品頁"},{b:"TSC",t:"工業型",s:"MH 系列",m:"MH641",status:"官網產品頁"},{b:"TSC",t:"工業型",s:"MH 系列",m:"MH640",status:"官網產品頁"},{b:"TSC",t:"工業型",s:"MB 系列",m:"MB240T",status:"官網產品頁"},{b:"TSC",t:"工業型",s:"MB 系列",m:"MB340T",status:"官網產品頁"},
{b:"TSC",t:"桌上型",s:"TX 系列",m:"TX610",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TH 系列",m:"TH240",status:"官網產品頁",note:"203 dpi；官網列熱轉／熱感、內建乙太網路"},{b:"TSC",t:"桌上型",s:"TH 系列",m:"TH340",status:"官網產品頁",note:"300 dpi"},{b:"TSC",t:"桌上型",s:"TE 系列",m:"TE210",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TE 系列",m:"TE310",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TE 系列",m:"TE200",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TE 系列",m:"TE300",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TTP 系列",m:"TTP-247",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TTP 系列",m:"TTP-345",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"TTP 系列",m:"TTP-244 PRO",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"DA 系列",m:"DA210",status:"官網產品頁"},{b:"TSC",t:"桌上型",s:"DA 系列",m:"DA220",status:"官網產品頁"},{b:"TSC",t:"攜帶型",s:"Alpha 系列",m:"Alpha-3R",status:"官網產品頁"},
{b:"GoDEX",t:"工業型",s:"GX 系列",m:"GX4200i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"GX 系列",m:"GX4300i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"GX 系列",m:"GX4600i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"ZX400i+ 系列",m:"ZX420i+",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"ZX400i+ 系列",m:"ZX430i+",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"ZX1000i+ 系列",m:"ZX1200i+",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"ZX1000i+ 系列",m:"ZX1300i+",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"ZX1000i+ 系列",m:"ZX1600i+",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"EZ 系列",m:"EZ2250i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"EZ 系列",m:"EZ2350i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"EZ 系列",m:"EZ6250i",status:"官網產品頁"},{b:"GoDEX",t:"工業型",s:"EZ 系列",m:"EZ6350i",status:"官網產品頁"},
{b:"GoDEX",t:"桌上型",s:"GE300 系列",m:"GE300",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"GE300 系列",m:"GE330",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"EZ100 系列",m:"EZ120",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"G500 系列",m:"G500+",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"G500 系列",m:"G530+",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"RT700i+ 系列",m:"RT700i+",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"RT700i+ 系列",m:"RT730i+",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"RT 系列",m:"RT863i+",status:"官網產品頁",note:"600 dpi 桌上型"},{b:"GoDEX",t:"桌上型",s:"DT 系列",m:"DT2x",status:"官網產品頁"},{b:"GoDEX",t:"桌上型",s:"G500 系列（舊）",m:"G500",status:"已停產",note:"接續型號 G500+ 系列"},{b:"GoDEX",t:"桌上型",s:"G500 系列（舊）",m:"G530",status:"已停產",note:"接續型號 G500+ 系列"},{b:"GoDEX",t:"桌上型",s:"EZ500 系列（舊）",m:"EZ520",status:"已停產",note:"官網標示接續 G500+ 系列"},{b:"GoDEX",t:"桌上型",s:"EZ500 系列（舊）",m:"EZ530",status:"已停產",note:"官網標示接續 G500+ 系列"},
{b:"TOSHIBA",t:"工業型",s:"BA400 系列",m:"BA410T",status:"官網產品頁"},{b:"TOSHIBA",t:"工業型",s:"B-EX 系列",m:"B-EX4T1",status:"官網產品頁"},{b:"TOSHIBA",t:"工業型",s:"B-EX 系列",m:"B-EX4T2",status:"官網產品頁"},{b:"TOSHIBA",t:"工業型",s:"B-EX 系列",m:"B-EX4T3",status:"官網產品頁"},{b:"TOSHIBA",t:"工業型",s:"B-EX 系列",m:"B-EX6T",status:"官網產品頁"},{b:"TOSHIBA",t:"桌上型",s:"BA400 系列",m:"BA420T",status:"官網產品頁"},{b:"TOSHIBA",t:"工業型",s:"SA4 系列（舊）",m:"SA4TM",status:"已停產",note:"官網標示已停產；新一代型號 BA410T"},
{b:"SATO",t:"工業型",s:"CL4-SXR",m:"CL4-SXR",status:"官網產品頁"},{b:"SATO",t:"工業型",s:"NX 系列",m:"CL4NX Plus",status:"官網產品頁"},
{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"PX 系列",m:"PX940",status:"官網產品頁"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"PM 系列",m:"PM45",status:"官網產品頁"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"PX240 系列",m:"PX240S",status:"官網產品頁"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class X（舊）",m:"H-4212X",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class X（舊）",m:"H-4310X",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class X（舊）",m:"H-4606X",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class（舊）",m:"H-4212",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class（舊）",m:"H-4310",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class（舊）",m:"H-4408",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"H-Class（舊）",m:"H-4606",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"I-Class Mark II（舊）",m:"I-4212e",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"I-Class Mark II（舊）",m:"I-4310e",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"I-Class Mark II（舊）",m:"I-4606e",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"M-Class Mark II（舊）",m:"M-4206",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"M-Class Mark II（舊）",m:"M-4210",status:"已停產"},{b:"Honeywell (Datamax/Intermec)",t:"工業型",s:"M-Class Mark II（舊）",m:"M-4308",status:"已停產"}
];
